### ISSUE TITLE
Can not npm install

### ISSUE THREAD

**Issue by muhfaris** [bikram-choudhury/sb-admin2-react-tmplate#1]
i have been error like below :

![image](https://user-images.githubusercontent.com/16787866/79891711-95359b80-842b-11ea-884e-e9926f8103ce.png)

how to solve ?

**Comment by bikram-choudhury** [comment]
Check your node version. It should be >12.x.x. 

If the issue still persists, with node@12.x.x, then run bellow command. It will resolve the issue.
`npm install --save core-js@^3`

**Comment by muhfaris** [comment]
@bikram-choudhury thanks for reply.

i solved with clean cache and then update
```
npm  cache clean --force
npm update
```
